version: '3'

services:
  nginxImersao:
    image: leorv/imersao11-nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./www:/usr/share/nginx/html
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imersao11
      MYSQL_PASSWORD: root
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  goapp:
    build: goapp/
    ports:
      - 8081:8081
    volumes:
      - ./goapp:/go/src/app